### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by ofirkris** [Evergrow/Det_Inpainting#1]
Thanks for sharing this great project!
Can you kindly share the checkpoints?

**Comment by Evergrow** [comment]
Thanks for your attention. The pre-trained models in Celeba-Hq and Places2 are released.

**Comment by ofirkris** [comment]
Thanks! Though the weights have aren't open for download and require confirmation on Google drive from owner

**Comment by Evergrow** [comment]
Sorry! The permission has been updated. Please try it again.
